
name: Testing
on:
  push:
    branches:
    - develop
jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macos-11.7
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 12.5
        run: sudo xcode-select -switch /Applications/Xcode_12.5.app
      - name: Testing iOS app
        run: exec ./.github/scripts/test_app.sh
